/* Should this be added as a secondary flyway config? */

ALTER TABLE casTicketRegistry.SERVICETICKET
  CHANGE CREATION_TIME OLD_CREATION_TIME bigint(20),
  CHANGE LAST_TIME_USED OLD_LAST_TIME_USED bigint(20),
  CHANGE PREVIOUS_LAST_TIME_USED OLD_PREVIOUS_LAST_TIME_USED bigint(20),
  ADD COLUMN CREATION_TIME datetime(6),
  ADD COLUMN LAST_TIME_USED datetime(6),
  ADD COLUMN PREVIOUS_LAST_TIME_USED datetime(6);

UPDATE casTicketRegistry.SERVICETICKET SET
  CREATION_TIME = FROM_UNIXTIME(OLD_CREATION_TIME),
  LAST_TIME_USED = FROM_UNIXTIME(OLD_LAST_TIME_USED),
  PREVIOUS_LAST_TIME_USED = FROM_UNIXTIME(OLD_PREVIOUS_LAST_TIME_USED);

ALTER TABLE casTicketRegistry.SERVICETICKET
  DROP COLUMN OLD_CREATION_TIME,
  DROP COLUMN OLD_LAST_TIME_USED,
  DROP COLUMN OLD_PREVIOUS_LAST_TIME_USED;

ALTER TABLE casTicketRegistry.TICKETGRANTINGTICKET
  CHANGE CREATION_TIME OLD_CREATION_TIME bigint(20),
  CHANGE LAST_TIME_USED OLD_LAST_TIME_USED bigint(20),
  CHANGE PREVIOUS_LAST_TIME_USED OLD_PREVIOUS_LAST_TIME_USED bigint(20),
  ADD COLUMN CREATION_TIME datetime(6),
  ADD COLUMN LAST_TIME_USED datetime(6),
  ADD COLUMN PREVIOUS_LAST_TIME_USED datetime(6);

UPDATE casTicketRegistry.TICKETGRANTINGTICKET SET
  CREATION_TIME = FROM_UNIXTIME(OLD_CREATION_TIME),
  LAST_TIME_USED = FROM_UNIXTIME(OLD_LAST_TIME_USED),
  PREVIOUS_LAST_TIME_USED = FROM_UNIXTIME(OLD_PREVIOUS_LAST_TIME_USED);

ALTER TABLE casTicketRegistry.TICKETGRANTINGTICKET
  DROP COLUMN OLD_CREATION_TIME,
  DROP COLUMN OLD_LAST_TIME_USED,
  DROP COLUMN OLD_PREVIOUS_LAST_TIME_USED;